name: app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  scoped_model: ^1.0.1
  rxdart: ^0.25.0
  http: ^0.13.1
  flutter_paystack: ^1.0.5
  json_annotation: ^4.0.1
  flutter_html: ^1.3.0
  flutter_swiper: ^1.1.6
  cached_network_image: ^2.5.1
  shared_preferences: ^2.0.5
  country_code_picker: ^2.0.1
  url_launcher: ^6.0.2
  timeago: ^3.0.2
  flutter_rating_bar: ^4.0.0
  webview_flutter: ^1.0.7
  font_awesome_flutter: ^9.0.0
  share: ^2.0.1
  place_picker: ^0.9.18
  location: ^4.1.1
  fluttertoast: 7.1.5
  sign_in_with_apple: ^3.0.0
  image_picker: ^0.7.3
  flutter_webview_plugin: 0.3.11
  smooth_star_rating: ^1.1.1
  flutter_facebook_login: ^3.0.0
  fab_circular_menu: ^0.1.4
  google_fonts: ^2.0.0
  # stripe_payment: ^1.0.11
  network_to_file_image: ^3.0.0
  #barcode_scan: ^3.0.1
  geocoder: ^0.2.1
  photo_view: ^0.11.1
  intro_slider: ^2.3.4
  # onesignal_flutter: ^3.0.0
  pin_code_fields: ^7.0.0
  gradient_input_border: ^1.0.0
  devicelocale: ^0.4.1
  lottie: ^1.0.1
  webview_cookie_manager: ^1.0.8
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.3.0
  flutter_icons: ^1.1.0
  #flutter_barcode_scanner: ^1.0.2
  firebase_messaging: ^10.0.1
  cloud_firestore:  ^1.0.2
  firebase_storage: 8.0.3
  firebase_analytics: ^7.1.1
  firebase_core:  ^1.2.1
  firebase_auth: ^1.0.1
  google_sign_in: ^4.5.9
  rounded_loading_button: ^1.0.18
  tinycolor: ^1.0.3
  flutter_local_notifications: ^5.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.1.4+1
  change_app_package_name: ^0.1.2
  flutter_launcher_icons: ^0.9.0

flutter_native_splash:
  image: lib/assets/images/splash.jpg
  color: "ffffff"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/images/intro/

  fonts:
    - family: MStoreIcons
      fonts:
        - asset: lib/assets/fonts/Icons/MStoreIcons.ttf